version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web/index.php:/var/www/html/index.php
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db

  git:
    image: alpine/git
    container_name: git_sync
    volumes:
      - ./web:/repo
    working_dir: /repo
    entrypoint: ["sh", "-c"]
    command: 
      - |
        git config --global --add safe.directory /repo
        if [ ! -d ".git" ]; then
          git clone https://github.com/Gemma-1/ProyectoAmpliacion.git .
        else
          git fetch origin
          git reset --hard origin/main
        fi
        # Aseguramos que el archivo se llame index.php para el volumen
        [ -f index.php ] || cp pagina.php index.php

volumes:
  db_data: